### ISSUE TITLE
oauth proxy needs additional permission to work in 4.9+

### ISSUE THREAD

**Issue by herbeck558** [IBM/acd-containers#128]
see https://github.com/openshift/oauth-proxy/issues/229
the docs use latest oauth proxy - 4.9+ requires additional role and a cert to exist.  
You'll see these errors in the oauth proxy logs when the permission is missing:
`E0408 10:45:20.426803       1 reflector.go:127] github.com/openshift/oauth-proxy/providers/openshift/provider.go:354: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "oauth-serving-cert" is forbidden: User "system:serviceaccount:ibm-wh-acd-oauth-proxy:proxy" cannot list resource "configmaps" in API group "" in the namespace "openshift-config-managed"
`

The work around (for now) is to revert to the 4.8 version of the openshift oauth proxy using
`image: 'registry.redhat.io/openshift4/ose-oauth-proxy:v4.8'`
In the sample yaml on step 2 in the [manage-access](https://ibm.github.io/acd-containers/security/manage-access/) instructions.

You can add a role and bind it as the issue above notes but then you also need to be on 4.9+ I believe.  suggest using v4.8 label for now.

**Comment by cagrev** [comment]
I saw this two days ago in the Truven Data Center too when working with Karen. They are on OCP 4.6. The error was present in the logs, but it didn't seem to cause an error when continuing to use the proxy for ACD calls.

I'll make the update in the sample yaml to use 4.8 for now.
